//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Preferences = new HashSet<Preference>();
            this.ToReadLists = new HashSet<ToReadList>();
            this.NewsSources = new HashSet<NewsSource>();
        }
    
        public long UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ssd { get; set; }
        public string UserProfile { get; set; }
    
        public virtual ICollection<Preference> Preferences { get; set; }
        public virtual ICollection<ToReadList> ToReadLists { get; set; }
        public virtual ICollection<NewsSource> NewsSources { get; set; }
    }
}
